---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cos-fleetshard-operator-camel
  labels:
    app.kubernetes.io/name: cos-fleetshard-operator-camel
    app.kubernetes.io/instance: cos-fleetshard-operator-camel
    app.kubernetes.io/component: cos-fleetshard-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cos-fleetshard-operator-camel
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: cos-fleetshard-operator-camel
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - args:
            - 'run'
            - '--operator-id'
            - 'cos-fleetshard'
            - '--operator-group'
            - 'cos.bf2.dev'
            - '--operator-type'
            - 'camel'
          image: 'quay.io/lburgazzoli/cos-fleetshard:latest'
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "camel-k"
            - name: OPERATOR_ID
              value: "camel-k"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: cos-fleetshard
      terminationGracePeriodSeconds: 10
