/*
Connector Service Fleet Manager Private APIs

Connector Service Fleet Manager apis that are used by internal services.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package controlplane

import (
	"encoding/json"
)

// ConnectorClusterPlatform information about the kubernetes platform
type ConnectorClusterPlatform struct {
	// the kubernetes cluster type
	Type *string `json:"type,omitempty"`
	// uniquely identifies the kubernetes cluster
	Id *string `json:"id,omitempty"`
	// optional version of the kubernetes cluster
	Version *string `json:"version,omitempty"`
}

// NewConnectorClusterPlatform instantiates a new ConnectorClusterPlatform object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorClusterPlatform() *ConnectorClusterPlatform {
	this := ConnectorClusterPlatform{}
	return &this
}

// NewConnectorClusterPlatformWithDefaults instantiates a new ConnectorClusterPlatform object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorClusterPlatformWithDefaults() *ConnectorClusterPlatform {
	this := ConnectorClusterPlatform{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ConnectorClusterPlatform) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorClusterPlatform) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ConnectorClusterPlatform) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ConnectorClusterPlatform) SetType(v string) {
	o.Type = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ConnectorClusterPlatform) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorClusterPlatform) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ConnectorClusterPlatform) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ConnectorClusterPlatform) SetId(v string) {
	o.Id = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ConnectorClusterPlatform) GetVersion() string {
	if o == nil || isNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorClusterPlatform) GetVersionOk() (*string, bool) {
	if o == nil || isNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ConnectorClusterPlatform) HasVersion() bool {
	if o != nil && !isNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ConnectorClusterPlatform) SetVersion(v string) {
	o.Version = &v
}

func (o ConnectorClusterPlatform) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorClusterPlatform struct {
	value *ConnectorClusterPlatform
	isSet bool
}

func (v NullableConnectorClusterPlatform) Get() *ConnectorClusterPlatform {
	return v.value
}

func (v *NullableConnectorClusterPlatform) Set(val *ConnectorClusterPlatform) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorClusterPlatform) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorClusterPlatform) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorClusterPlatform(val *ConnectorClusterPlatform) *NullableConnectorClusterPlatform {
	return &NullableConnectorClusterPlatform{value: val, isSet: true}
}

func (v NullableConnectorClusterPlatform) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorClusterPlatform) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
