/*
Connector Service Fleet Manager Private APIs

Connector Service Fleet Manager apis that are used by internal services.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package controlplane

import (
	"encoding/json"
)

// ConnectorDeploymentWatchEventAllOf struct for ConnectorDeploymentWatchEventAllOf
type ConnectorDeploymentWatchEventAllOf struct {
	Object *ConnectorDeployment `json:"object,omitempty"`
}

// NewConnectorDeploymentWatchEventAllOf instantiates a new ConnectorDeploymentWatchEventAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorDeploymentWatchEventAllOf() *ConnectorDeploymentWatchEventAllOf {
	this := ConnectorDeploymentWatchEventAllOf{}
	return &this
}

// NewConnectorDeploymentWatchEventAllOfWithDefaults instantiates a new ConnectorDeploymentWatchEventAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorDeploymentWatchEventAllOfWithDefaults() *ConnectorDeploymentWatchEventAllOf {
	this := ConnectorDeploymentWatchEventAllOf{}
	return &this
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ConnectorDeploymentWatchEventAllOf) GetObject() ConnectorDeployment {
	if o == nil || isNil(o.Object) {
		var ret ConnectorDeployment
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorDeploymentWatchEventAllOf) GetObjectOk() (*ConnectorDeployment, bool) {
	if o == nil || isNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ConnectorDeploymentWatchEventAllOf) HasObject() bool {
	if o != nil && !isNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given ConnectorDeployment and assigns it to the Object field.
func (o *ConnectorDeploymentWatchEventAllOf) SetObject(v ConnectorDeployment) {
	o.Object = &v
}

func (o ConnectorDeploymentWatchEventAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorDeploymentWatchEventAllOf struct {
	value *ConnectorDeploymentWatchEventAllOf
	isSet bool
}

func (v NullableConnectorDeploymentWatchEventAllOf) Get() *ConnectorDeploymentWatchEventAllOf {
	return v.value
}

func (v *NullableConnectorDeploymentWatchEventAllOf) Set(val *ConnectorDeploymentWatchEventAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorDeploymentWatchEventAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorDeploymentWatchEventAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorDeploymentWatchEventAllOf(val *ConnectorDeploymentWatchEventAllOf) *NullableConnectorDeploymentWatchEventAllOf {
	return &NullableConnectorDeploymentWatchEventAllOf{value: val, isSet: true}
}

func (v NullableConnectorDeploymentWatchEventAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorDeploymentWatchEventAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
