/*
Connector Service Fleet Manager Private APIs

Connector Service Fleet Manager apis that are used by internal services.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package controlplane

import (
	"encoding/json"
)

// ConnectorNamespaceDeploymentListAllOf struct for ConnectorNamespaceDeploymentListAllOf
type ConnectorNamespaceDeploymentListAllOf struct {
	Items []ConnectorNamespaceDeployment `json:"items,omitempty"`
}

// NewConnectorNamespaceDeploymentListAllOf instantiates a new ConnectorNamespaceDeploymentListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorNamespaceDeploymentListAllOf() *ConnectorNamespaceDeploymentListAllOf {
	this := ConnectorNamespaceDeploymentListAllOf{}
	return &this
}

// NewConnectorNamespaceDeploymentListAllOfWithDefaults instantiates a new ConnectorNamespaceDeploymentListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorNamespaceDeploymentListAllOfWithDefaults() *ConnectorNamespaceDeploymentListAllOf {
	this := ConnectorNamespaceDeploymentListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ConnectorNamespaceDeploymentListAllOf) GetItems() []ConnectorNamespaceDeployment {
	if o == nil || isNil(o.Items) {
		var ret []ConnectorNamespaceDeployment
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNamespaceDeploymentListAllOf) GetItemsOk() ([]ConnectorNamespaceDeployment, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ConnectorNamespaceDeploymentListAllOf) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ConnectorNamespaceDeployment and assigns it to the Items field.
func (o *ConnectorNamespaceDeploymentListAllOf) SetItems(v []ConnectorNamespaceDeployment) {
	o.Items = v
}

func (o ConnectorNamespaceDeploymentListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorNamespaceDeploymentListAllOf struct {
	value *ConnectorNamespaceDeploymentListAllOf
	isSet bool
}

func (v NullableConnectorNamespaceDeploymentListAllOf) Get() *ConnectorNamespaceDeploymentListAllOf {
	return v.value
}

func (v *NullableConnectorNamespaceDeploymentListAllOf) Set(val *ConnectorNamespaceDeploymentListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorNamespaceDeploymentListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorNamespaceDeploymentListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorNamespaceDeploymentListAllOf(val *ConnectorNamespaceDeploymentListAllOf) *NullableConnectorNamespaceDeploymentListAllOf {
	return &NullableConnectorNamespaceDeploymentListAllOf{value: val, isSet: true}
}

func (v NullableConnectorNamespaceDeploymentListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorNamespaceDeploymentListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
