/*
Connector Service Fleet Manager Private APIs

Connector Service Fleet Manager apis that are used by internal services.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package controlplane

import (
	"encoding/json"
)

// ConnectorNamespaceDeploymentList struct for ConnectorNamespaceDeploymentList
type ConnectorNamespaceDeploymentList struct {
	Kind  string                         `json:"kind"`
	Page  int32                          `json:"page"`
	Size  int32                          `json:"size"`
	Total int32                          `json:"total"`
	Items []ConnectorNamespaceDeployment `json:"items"`
}

// NewConnectorNamespaceDeploymentList instantiates a new ConnectorNamespaceDeploymentList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorNamespaceDeploymentList(kind string, page int32, size int32, total int32, items []ConnectorNamespaceDeployment) *ConnectorNamespaceDeploymentList {
	this := ConnectorNamespaceDeploymentList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewConnectorNamespaceDeploymentListWithDefaults instantiates a new ConnectorNamespaceDeploymentList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorNamespaceDeploymentListWithDefaults() *ConnectorNamespaceDeploymentList {
	this := ConnectorNamespaceDeploymentList{}
	return &this
}

// GetKind returns the Kind field value
func (o *ConnectorNamespaceDeploymentList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ConnectorNamespaceDeploymentList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ConnectorNamespaceDeploymentList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *ConnectorNamespaceDeploymentList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ConnectorNamespaceDeploymentList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ConnectorNamespaceDeploymentList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ConnectorNamespaceDeploymentList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ConnectorNamespaceDeploymentList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ConnectorNamespaceDeploymentList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ConnectorNamespaceDeploymentList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ConnectorNamespaceDeploymentList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ConnectorNamespaceDeploymentList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *ConnectorNamespaceDeploymentList) GetItems() []ConnectorNamespaceDeployment {
	if o == nil {
		var ret []ConnectorNamespaceDeployment
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ConnectorNamespaceDeploymentList) GetItemsOk() ([]ConnectorNamespaceDeployment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ConnectorNamespaceDeploymentList) SetItems(v []ConnectorNamespaceDeployment) {
	o.Items = v
}

func (o ConnectorNamespaceDeploymentList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["page"] = o.Page
	}
	if true {
		toSerialize["size"] = o.Size
	}
	if true {
		toSerialize["total"] = o.Total
	}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorNamespaceDeploymentList struct {
	value *ConnectorNamespaceDeploymentList
	isSet bool
}

func (v NullableConnectorNamespaceDeploymentList) Get() *ConnectorNamespaceDeploymentList {
	return v.value
}

func (v *NullableConnectorNamespaceDeploymentList) Set(val *ConnectorNamespaceDeploymentList) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorNamespaceDeploymentList) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorNamespaceDeploymentList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorNamespaceDeploymentList(val *ConnectorNamespaceDeploymentList) *NullableConnectorNamespaceDeploymentList {
	return &NullableConnectorNamespaceDeploymentList{value: val, isSet: true}
}

func (v NullableConnectorNamespaceDeploymentList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorNamespaceDeploymentList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
