/*
Connector Service Fleet Manager Private APIs

Connector Service Fleet Manager apis that are used by internal services.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package controlplane

import (
	"encoding/json"
)

// ConnectorDeploymentList struct for ConnectorDeploymentList
type ConnectorDeploymentList struct {
	Kind  string                `json:"kind"`
	Page  int32                 `json:"page"`
	Size  int32                 `json:"size"`
	Total int32                 `json:"total"`
	Items []ConnectorDeployment `json:"items"`
}

// NewConnectorDeploymentList instantiates a new ConnectorDeploymentList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorDeploymentList(kind string, page int32, size int32, total int32, items []ConnectorDeployment) *ConnectorDeploymentList {
	this := ConnectorDeploymentList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewConnectorDeploymentListWithDefaults instantiates a new ConnectorDeploymentList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorDeploymentListWithDefaults() *ConnectorDeploymentList {
	this := ConnectorDeploymentList{}
	return &this
}

// GetKind returns the Kind field value
func (o *ConnectorDeploymentList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ConnectorDeploymentList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ConnectorDeploymentList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *ConnectorDeploymentList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ConnectorDeploymentList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ConnectorDeploymentList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *ConnectorDeploymentList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ConnectorDeploymentList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ConnectorDeploymentList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *ConnectorDeploymentList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ConnectorDeploymentList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ConnectorDeploymentList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *ConnectorDeploymentList) GetItems() []ConnectorDeployment {
	if o == nil {
		var ret []ConnectorDeployment
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ConnectorDeploymentList) GetItemsOk() ([]ConnectorDeployment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ConnectorDeploymentList) SetItems(v []ConnectorDeployment) {
	o.Items = v
}

func (o ConnectorDeploymentList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["page"] = o.Page
	}
	if true {
		toSerialize["size"] = o.Size
	}
	if true {
		toSerialize["total"] = o.Total
	}
	if true {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorDeploymentList struct {
	value *ConnectorDeploymentList
	isSet bool
}

func (v NullableConnectorDeploymentList) Get() *ConnectorDeploymentList {
	return v.value
}

func (v *NullableConnectorDeploymentList) Set(val *ConnectorDeploymentList) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorDeploymentList) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorDeploymentList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorDeploymentList(val *ConnectorDeploymentList) *NullableConnectorDeploymentList {
	return &NullableConnectorDeploymentList{value: val, isSet: true}
}

func (v NullableConnectorDeploymentList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorDeploymentList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
