/*
Connector Service Fleet Manager Private APIs

Connector Service Fleet Manager apis that are used by internal services.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package controlplane

import (
	"encoding/json"
)

// ConnectorDeploymentStatusOperators struct for ConnectorDeploymentStatusOperators
type ConnectorDeploymentStatusOperators struct {
	Assigned  *ConnectorOperator `json:"assigned,omitempty"`
	Available *ConnectorOperator `json:"available,omitempty"`
}

// NewConnectorDeploymentStatusOperators instantiates a new ConnectorDeploymentStatusOperators object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorDeploymentStatusOperators() *ConnectorDeploymentStatusOperators {
	this := ConnectorDeploymentStatusOperators{}
	return &this
}

// NewConnectorDeploymentStatusOperatorsWithDefaults instantiates a new ConnectorDeploymentStatusOperators object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorDeploymentStatusOperatorsWithDefaults() *ConnectorDeploymentStatusOperators {
	this := ConnectorDeploymentStatusOperators{}
	return &this
}

// GetAssigned returns the Assigned field value if set, zero value otherwise.
func (o *ConnectorDeploymentStatusOperators) GetAssigned() ConnectorOperator {
	if o == nil || isNil(o.Assigned) {
		var ret ConnectorOperator
		return ret
	}
	return *o.Assigned
}

// GetAssignedOk returns a tuple with the Assigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorDeploymentStatusOperators) GetAssignedOk() (*ConnectorOperator, bool) {
	if o == nil || isNil(o.Assigned) {
		return nil, false
	}
	return o.Assigned, true
}

// HasAssigned returns a boolean if a field has been set.
func (o *ConnectorDeploymentStatusOperators) HasAssigned() bool {
	if o != nil && !isNil(o.Assigned) {
		return true
	}

	return false
}

// SetAssigned gets a reference to the given ConnectorOperator and assigns it to the Assigned field.
func (o *ConnectorDeploymentStatusOperators) SetAssigned(v ConnectorOperator) {
	o.Assigned = &v
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *ConnectorDeploymentStatusOperators) GetAvailable() ConnectorOperator {
	if o == nil || isNil(o.Available) {
		var ret ConnectorOperator
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorDeploymentStatusOperators) GetAvailableOk() (*ConnectorOperator, bool) {
	if o == nil || isNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *ConnectorDeploymentStatusOperators) HasAvailable() bool {
	if o != nil && !isNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given ConnectorOperator and assigns it to the Available field.
func (o *ConnectorDeploymentStatusOperators) SetAvailable(v ConnectorOperator) {
	o.Available = &v
}

func (o ConnectorDeploymentStatusOperators) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Assigned) {
		toSerialize["assigned"] = o.Assigned
	}
	if !isNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorDeploymentStatusOperators struct {
	value *ConnectorDeploymentStatusOperators
	isSet bool
}

func (v NullableConnectorDeploymentStatusOperators) Get() *ConnectorDeploymentStatusOperators {
	return v.value
}

func (v *NullableConnectorDeploymentStatusOperators) Set(val *ConnectorDeploymentStatusOperators) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorDeploymentStatusOperators) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorDeploymentStatusOperators) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorDeploymentStatusOperators(val *ConnectorDeploymentStatusOperators) *NullableConnectorDeploymentStatusOperators {
	return &NullableConnectorDeploymentStatusOperators{value: val, isSet: true}
}

func (v NullableConnectorDeploymentStatusOperators) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorDeploymentStatusOperators) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
