apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bf2-cos-fleetshard-go
    app.kubernetes.io/part-of: bf2-cos-fleetshard-go
    app.kubernetes.io/managed-by: kustomize
  name: cos-fleetshard-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cos-fleetshard-cluster-role
subjects:
- kind: ServiceAccount
  name: cos-fleetshard
  namespace: cos-fleetshard-system
