---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cos-fleetshard-cluster-role
rules:
#
# core
#
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
#
# camel-k
#
- apiGroups:
  - camel.apache.org
  resources:
  - kameletbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

#
# Managed Connector Clusters
#
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters/finalizers
  verbs:
  - update
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters/status
  verbs:
  - get
  - patch
  - update

#
# Managed Connectors
#
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectors/finalizers
  verbs:
  - update
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectors/status
  verbs:
  - get
  - patch
  - update

#
# Managed Connector Operators
#
- apiGroups:
    - cos.bf2.dev
  resources:
    - managedconnectoroperators
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cos.bf2.dev
  resources:
    - managedconnectoroperators/finalizers
  verbs:
    - update
- apiGroups:
    - cos.bf2.dev
  resources:
    - managedconnectoroperators/status
  verbs:
    - get
    - patch
    - update