# permissions for end users to edit managedconnectorclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedconnectorcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bf2-cos-fleetshard-go
    app.kubernetes.io/part-of: bf2-cos-fleetshard-go
    app.kubernetes.io/managed-by: kustomize
  name: managedconnectorcluster-editor-role
rules:
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters/status
  verbs:
  - get
