# permissions for end users to edit managedconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedconnector-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bf2-cos-fleetshard-go
    app.kubernetes.io/part-of: bf2-cos-fleetshard-go
    app.kubernetes.io/managed-by: kustomize
  name: managedconnector-editor-role
rules:
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectors/status
  verbs:
  - get
