---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - camel.apache.org
  resources:
  - kameletbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters/finalizers
  verbs:
  - update
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectorclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectors/finalizers
  verbs:
  - update
- apiGroups:
  - cos.bf2.dev
  resources:
  - managedconnectors/status
  verbs:
  - get
  - patch
  - update
