---
apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: camel-k
---
apiVersion: cos.bf2.dev/v2
kind:  ManagedConnectorCluster
metadata:
  name: 'lb-dev'
spec:
  secret: 'addon-connectors-operator-parameters'
  pollDelay: '10s'
  resyncDelay: '60s'