
generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: camel-k

resources:
  - resources/cluster-role-camel-k-operator.yaml
  - resources/cluster-role-camel-k-operator-openshift.yaml
  - resources/camel-catalog.yaml
  - https://github.com/apache/camel-k//config/crd/?ref=release-1.11.x
  - https://github.com/apache/camel-k//config/rbac/?ref=release-1.11.x
  - https://github.com/apache/camel-k//config/rbac/openshift/?ref=release-1.11.x

patchesStrategicMerge:
- patches/delete-camel-k-edit.yaml
- patches/delete-camel-k-clusterrole-console.yaml
- patches/delete-camel-k-clusterrole-console-binding.yaml
- patches/delete-camel-k-role-operator.yaml
- patches/delete-camel-k-role-operator-openshift.yaml
- patches/delete-camel-k-role-knative.yaml
- patches/delete-camel-k-role-keda.yaml
- patches/delete-camel-k-role-strimzi.yaml
- patches/delete-camel-k-rolebinding-knative.yaml
- patches/delete-camel-k-rolebinding-keda.yaml
- patches/delete-camel-k-rolebinding-strimzi.yaml

patches:
  - path: patches/patch-roles.yaml
    target:
      group: rbac.authorization.k8s.io
      kind: Role
      name: camel-k-operator.*
      version: v1
  - path: patches/patch-rolebindings.yaml
    target:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: camel-k-operator.*
      version: v1
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: builds.camel.apache.org
    patch: |-
      - op: replace
        path: /metadata/name
        value: "builds.cos.bf2.dev"
      - op: replace
        path: /spec/group
        value: "cos.bf2.dev"
      - op: replace
        path: /spec/versions/0/name
        value: "v2"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: camelcatalogs.camel.apache.org
    patch: |-
      - op: replace
        path: /metadata/name
        value: "camelcatalogs.cos.bf2.dev"
      - op: replace
        path: /spec/group
        value: "cos.bf2.dev"
      - op: replace
        path: /spec/versions/0/name
        value: "v2"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: integrationkits.camel.apache.org
    patch: |-
      - op: replace
        path: /metadata/name
        value: "integrationkits.cos.bf2.dev"
      - op: replace
        path: /spec/group
        value: "cos.bf2.dev"
      - op: replace
        path: /spec/versions/0/name
        value: "v2"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: integrationplatforms.camel.apache.org
    patch: |-
      - op: replace
        path: /metadata/name
        value: "integrationplatforms.cos.bf2.dev"
      - op: replace
        path: /spec/group
        value: "cos.bf2.dev"
      - op: replace
        path: /spec/versions/0/name
        value: "v2"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: integrations.camel.apache.org
    patch: |-
      - op: replace
        path: /metadata/name
        value: "integrations.cos.bf2.dev"
      - op: replace
        path: /spec/group
        value: "cos.bf2.dev"
      - op: replace
        path: /spec/versions/0/name
        value: "v2"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: kameletbindings.camel.apache.org
    patch: |-
      - op: replace
        path: /metadata/name
        value: "kameletbindings.cos.bf2.dev"
      - op: replace
        path: /spec/group
        value: "cos.bf2.dev"
      - op: replace
        path: /spec/versions/0/name
        value: "v2"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: kamelets.camel.apache.org
    patch: |-
      - op: replace
        path: /metadata/name
        value: "kamelets.cos.bf2.dev"
      - op: replace
        path: /spec/group
        value: "cos.bf2.dev"
      - op: replace
        path: /spec/versions/0/name
        value: "v2"
