package meta

const MetaUnitOfWork string = "cos.bf2.dev/uow"
const MetaDeploymentID string = "cos.bf2.dev/deployment.id"
const MetaDeploymentRevision string = "cos.bf2.dev/deployment.revision"
const MetaConnectorID string = "cos.bf2.dev/connector.id"
const MetaConnectorRevision string = "cos.bf2.dev/connector.revision"
const MetaConnectorTypeID string = "cos.bf2.dev/connector.type.id"
const MetaOperatorID string = "cos.bf2.dev/operator.id"
const MetaOperatorType string = "cos.bf2.dev/operator.type"
const MetaOperatorVersion string = "cos.bf2.dev/operator.version"
const MetaOperatorGroup string = "cos.bf2.dev/operator.group"
const MetaClusterID string = "cos.bf2.dev/cluster.id"
const MetaNamespaceID string = "cos.bf2.dev/namespace.id"
const MetaNamespaceRevision string = "cos.bf2.dev/namespace.revision"
