name: Build

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Build
        run: |
          make test
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
  publish:
    name: Publish
    needs:
    - build
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.CONTAINER_REEGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REEGISTRY_PASSWORD }}
      - name: Publish
        run: |
          make image/publish